table Dim_Calendario
	lineageTag: c805c21f-bb09-4b69-8811-189967a542b3

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5d6bbdf7-67d3-4855-b7c0-bde3b866aae7
		summarizeBy: none
		sourceColumn: Fecha

		variation Variation
			isDefault
			relationship: 887b441b-91e9-4034-bcc7-c5df978ee1d4
			defaultHierarchy: LocalDateTable_dad6863a-dee4-4783-96a5-9b7cf5a50af0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: 5eb190a9-6d05-4d08-9c4b-cc6e712e7b45
		summarizeBy: sum
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Semana
		dataType: int64
		formatString: 0
		lineageTag: 5695dc45-f4a5-401c-9967-75f78172df50
		summarizeBy: sum
		sourceColumn: Semana

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: 4209cbef-543b-4799-bb98-c59b764267ee
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column 'Numero Mes'
		dataType: int64
		formatString: 0
		lineageTag: 974019bd-4722-49fd-a538-5c85065d8869
		summarizeBy: sum
		sourceColumn: Numero Mes

		annotation SummarizationSetBy = Automatic

	column datekey
		dataType: int64
		formatString: 0
		lineageTag: 6e53035c-7e76-479d-a871-aabc0383f1a5
		summarizeBy: none
		sourceColumn: datekey

		annotation SummarizationSetBy = Automatic

	partition Dim_Calendario = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\fer20\Downloads\VentasVehiculos.xlsx"), null, true),
				    Dim_Calendario_Table = Source{[Item="Dim_Calendario",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Dim_Calendario_Table,{{"Fecha", type date}, {"Año", Int64.Type}, {"Semana", Int64.Type}, {"Mes", type text}, {"Numero Mes", Int64.Type}, {"datekey", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

