table Dim_Cliente
	lineageTag: f45e5ff6-f1dd-4643-9bb9-0dd986083c16

	column id_Cliente
		dataType: int64
		formatString: 0
		lineageTag: 39da306b-1597-4982-bf92-6d17e949a67d
		summarizeBy: none
		sourceColumn: id_Cliente

		annotation SummarizationSetBy = Automatic

	column Nombre
		dataType: string
		lineageTag: a8833ccf-5cb4-4b6a-8f99-71e1ca42c902
		summarizeBy: none
		sourceColumn: Nombre

		annotation SummarizationSetBy = Automatic

	partition Dim_Cliente = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\fer20\Downloads\VentasVehiculos.xlsx"), null, true),
				    Dim_Cliente_Table = Source{[Item="Dim_Cliente",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Dim_Cliente_Table,{{"id_Cliente", Int64.Type}, {"Nombre", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

